# Generated by Django 5.2.7 on 2025-10-30 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('V', 'Vocales'), ('C', 'Consonantes')], max_length=1)),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Media'), ('D', 'Difícil')], max_length=1)),
                ('imagen', models.ImageField(upload_to='letras/')),
                ('contorno', models.JSONField(default=list)),
                ('trazos', models.JSONField(default=list)),
                ('precio_xp', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('letras_practicadas', models.ManyToManyField(blank=True, to='infrastructure.letra')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='infrastructure.letra')),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='infrastructure.perfilusuario')),
            ],
            options={
                'unique_together': {('letra', 'perfil_usuario')},
            },
        ),
    ]
