# Generated by Django 5.2.7 on 2025-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_letra_perfilusuario_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letra',
            name='contorno',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='letra',
            name='trazos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
