# Generated by Django 5.2.7 on 2025-10-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_letra_contorno_alter_letra_trazos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Media'), ('D', 'Difícil')], max_length=1)),
                ('imagen', models.ImageField(upload_to='numeros/')),
                ('contorno', models.JSONField(blank=True, default=list)),
                ('trazos', models.JSONField(blank=True, default=list)),
                ('precio_xp', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
