# Generated by Django 5.2.7 on 2025-11-01 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_letracompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='letracompra',
            name='letra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.letra'),
        ),
        migrations.AddConstraint(
            model_name='letracompra',
            constraint=models.UniqueConstraint(fields=('usuario', 'letra'), name='unique_usuario_letra'),
        ),
    ]
