# Generated by Django 5.2.7 on 2025-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_alter_letracompra_letra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letracompra',
            name='letra',
            field=models.CharField(max_length=5),
        ),
    ]
