# Generated by Django 5.2.7 on 2025-11-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_alter_letracompra_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letracompra',
            name='letra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.letra'),
        ),
    ]
