# Generated by Django 5.2.7 on 2025-11-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_alter_letracompra_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='letra',
            name='bloqueada',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='letras_desbloqueadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_desbloqueados', to='infrastructure.letra'),
        ),
    ]
