# Generated by Django 5.2.7 on 2025-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_letra_bloqueada_perfilusuario_letras_desbloqueadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Media'), ('D', 'Difícil')], max_length=2)),
                ('bloqueada', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='silabas')),
            ],
            options={
                'verbose_name_plural': 'Silabas',
            },
        ),
    ]
