# Generated by Django 5.2.7 on 2025-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_silaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='silaba',
            name='contorno',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='silaba',
            name='trazos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
