# Generated by Django 5.2.7 on 2025-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_silaba_contorno_silaba_trazos'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modules/'),
        ),
    ]
