# Generated by Django 5.1.4 on 2025-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_module_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='silabas_desbloqueadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_desbloqueados_silabas', to='infrastructure.silaba'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='silabas_practicadas',
            field=models.ManyToManyField(blank=True, to='infrastructure.silaba'),
        ),
    ]
